### ISSUE TITLE
ImageView and PyPlot don't like each other

### ISSUE THREAD

**Issue by felixhorger** [JuliaImages/ImageView.jl#262] opened 2022-03-25 12:34 UTC
When importing both ImageView and PyPlot, two errors occur depending on the order:

1)
```
import ImageView
import PyPlot as plt

plt.figure()
```
gives a segfault
```
PyErr_CheckSignals at /usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0 (unknown line)
PyObject_Repr at /usr/lib/x86_64-linux-gnu/libpython3.9.so.1.0 (unknown line)
pystring at /home/felix/.julia/packages/PyCall/7a7w0/src/PyCall.jl:243
show at /home/felix/.julia/packages/PyCall/7a7w0/src/PyCall.jl:257
unknown function (ip: 0x7fbf012c0ba9)
```

2)
```
import PyPlot as plt
import ImageView
```

gives 
```
ERROR: InitError: could not load library "/home/felix/.julia/artifacts/6fe4ba8f1e130eb940af999b5c82fc4621d6719c/lib/libpango-1.0.so"
/home/felix/.julia/artifacts/6fe4ba8f1e130eb940af999b5c82fc4621d6719c/lib/libpango-1.0.so: undefined symbol: g_memdup2
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:117
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/QpMQW/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ Pango_jll ~/.julia/packages/Pango_jll/xt19s/src/wrappers/x86_64-linux-gnu.jl:16
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [7] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
  [9] _tryrequire_from_serialized(modkey::Base.PkgId, build_id::UInt64, modpath::String)
    @ Base ./loading.jl:783
 [10] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:843
 [11] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
 [12] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
 [13] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
during initialization of module Pango_jll
```

Both packages are updated to the newest version (julia version is 1.7.0)

**Comment by timholy** [comment] 2022-04-24 09:44
Duplicate of #149

**Closed by timholy** 2022-04-24 09:44 UTC
