### ISSUE TITLE
ERROR: objects of type Cairo.#destroy cannot be finalized

### ISSUE THREAD

**Issue by coolsecu** [JuliaImages/ImageView.jl#133] opened 2017-12-05 06:35 UTC
julia> imshow(img)
Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}(Pair{String,Any}("window", Gtk.GtkWindowLea…
  "roi"         => Dict{String,Any}(Pair{String,Any}("redraw", 73: "map(clim-ma…
  "annotations" => 5: "input-4" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 4: "CLim" = ImageView.CLim{FixedPointNumbers.Normed{UInt16,1…

julia> FATAL ERROR: Gtk state corrupted by error thrown in a callback:
ERROR: objects of type Cairo.#destroy cannot be finalized
Stacktrace:
 [1] finalizer at ./base.jl:127 [inlined]
 [2] Type at /Users/xitongliang/.julia/v0.6/Cairo/src/Cairo.jl:131 [inlined]
 [3] Type at /Users/xitongliang/.julia/v0.6/Cairo/src/Cairo.jl:149 [inlined]
 [4] cairo_surface_for(::Gtk.GtkCanvas) at /Users/xitongliang/.julia/v0.6/Gtk/src/cairo.jl:92
 [5] notify_resize(::Ptr{Gtk.GLib.GObject}, ::Ptr{Gtk.GdkRectangle}, ::Gtk.GtkCanvas) at /Users/xitongliang/.julia/v0.6/Gtk/src/cairo.jl:56
 [6] (::Gtk.##229#230)() at /Users/xitongliang/.julia/v0.6/Gtk/src/events.jl:2
 [7] g_sigatom(::Any) at /Users/xitongliang/.julia/v0.6/Gtk/src/GLib/signals.jl:167
 [8] gtk_main() at /Users/xitongliang/.julia/v0.6/Gtk/src/events.jl:1

**Comment by timholy** [comment] 2017-12-05 09:28
Duplicate of #132.

**Closed by timholy** 2017-12-05 09:28 UTC
